apiVersion: v1
kind: Service
metadata:
  name: crapi-identity
  labels:
    app: crapi-identity
spec:
  ports:
  - port: {{ .Values.identity.port }}
    name: java
  selector:
    app: crapi-identity
