apiVersion: v1
kind: Service
metadata:
  name: crapi-community
  labels:
    app: crapi-community
spec:
  ports:
  - port: {{ .Values.community.port }}
    name: go
  selector:
    app: crapi-community
