apiVersion: v1
kind: Service
metadata:
  name: crapi-workshop
  labels:
    app: crapi-workshop
spec:
  ports:
  - port: {{ .Values.workshop.port }}
    name: python
  selector:
    app: crapi-workshop
