name: Build and Publish crAPI Images
on:
  push:
    branches-ignore:
      - main
      - snyk*

jobs:
  build-and-publish-images:
    runs-on: ubuntu-20.04
    environment: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Publish Community
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKER_REPO }}/crapi-community:${{ secrets.DOCKER_TAG }}
          platforms: linux/amd64,linux/arm